# Bootloader
TARGET_BOOTLOADER_BOARD_NAME :=
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM :=
TARGET_BOARD_PLATFORM_GPU :=

# Architecture
TARGET_ARCH :=
TARGET_ARCH_VARIANT :=
TARGET_CPU_ABI :=
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT :=

# For arm64
TARGET_2ND_ARCH :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_CPU_VARIANT :=

# Kernel
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE :=
BOARD_KERNEL_PAGESIZE :=
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00000000 --ramdisk_offset 0x00000000 --dt device/vendor/codename/dt.img --tags_offset 0x00000000
BOARD_KERNEL_SEPARATED_DT :=
TARGET_PREBUILT_KERNEL := device/vendor/codename/kernel

# Partition info
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_PLATFORM_DEVICE_BASE :=
BOARD_BOOTIMAGE_PARTITION_SIZE :=
BOARD_RECOVERYIMAGE_PARTITION_SIZE :=
BOARD_SYSTEMIMAGE_PARTITION_SIZE :=
BOARD_USERDATAIMAGE_PARTITION_SIZE :=
BOARD_FLASH_BLOCK_SIZE :=

# TWRP
TW_THEME :=

